services:
    app:
        image: hanabosocom/php-dev:php-8.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www:cached
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            - APP_ENV=dev
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - COMPOSER_HOME=${HOME}/dev/.composer
            - SMTP_TRANSPORT=${SMTP_TRANSPORT}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}

    smtp:
        image: mailhog/mailhog
        ports:
            - ${DEV_IP}:1025:1025
            - ${DEV_IP}:8025:8025
