monolog:
    use_microseconds: false
    channels: [mailer]
    handlers:
        mailer:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            channels: [mailer]